//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Owin.Security.ActiveDirectoryLDAP {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Owin.Security.ActiveDirectoryLDAP.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A day only has 24 hours..
        /// </summary>
        internal static string DayHours {
            get {
                return ResourceManager.GetString("DayHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A day starts at midnight..
        /// </summary>
        internal static string DayMidnight {
            get {
                return ResourceManager.GetString("DayMidnight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A day only has 1440 minutes..
        /// </summary>
        internal static string DayMinutes {
            get {
                return ResourceManager.GetString("DayMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid claim type..
        /// </summary>
        internal static string InvalidClaimType {
            get {
                return ResourceManager.GetString("InvalidClaimType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim value format could not be detected..
        /// </summary>
        internal static string InvalidClaimValue {
            get {
                return ResourceManager.GetString("InvalidClaimValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing required callback path..
        /// </summary>
        internal static string MissingCallbackPath {
            get {
                return ResourceManager.GetString("MissingCallbackPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing required password key..
        /// </summary>
        internal static string MissingPasswordKey {
            get {
                return ResourceManager.GetString("MissingPasswordKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing required state key..
        /// </summary>
        internal static string MissingStateKey {
            get {
                return ResourceManager.GetString("MissingStateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing required username key..
        /// </summary>
        internal static string MissingUsernameKey {
            get {
                return ResourceManager.GetString("MissingUsernameKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserPrincipal is missing a Guid..
        /// </summary>
        internal static string MissingUserPrincipalGuid {
            get {
                return ResourceManager.GetString("MissingUserPrincipalGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserPrincipal is missing a Sid..
        /// </summary>
        internal static string MissingUserPrincipalSid {
            get {
                return ResourceManager.GetString("MissingUserPrincipalSid", resourceCulture);
            }
        }
    }
}
